name: gca
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=3.10
- r-base=4.4
- r-dplyr=1.0.10
- r-seurat=5.2.1
- r-compositions=2.0
- scanpy=1.11.0
- scikit-learn=1.6.0
- numpy=2.2.3
- pandas=2.2.3